language: python
os:
- linux
#- osx
sudo: required
python:
- '3.2'
#- '3.3'
#- '3.4'
#- '3.5'
- '3.6'
sudo: false
install:
- sudo apt-get install samtools
- pip install .
- pip install -r requirements.txt
script:
- make test
