name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

    jobs:

build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev
          python -m pip install --upgrade pip
          pip install pysam

      - name: Run tests
        run: make test

