name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    environment: publish
    permissions:
      id-token: write   # required
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheel & sdist
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI (Trusted Publishers)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

